# Base image with Python and PyTorch
FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

# Install dependencies
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy code
COPY server1.py client1.py ./

# Default command (override in compose)
CMD ["python", "server.py"]