[project]
name = "cifar10"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "ruff>=0.11.8",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
]
